# Generated by Django 5.1.1 on 2024-09-07 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Computer', 'Computers'), ('Laptop', 'Laptops'), ('Games', 'Games'), ('Phones', 'Phones'), ('Food', 'Food'), ('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Beauty', 'Beauty & Personal Care'), ('Books', 'Books'), ('Toys', 'Toys & Games'), ('Jewelry', 'Jewelry'), ('Sports', 'Sports & Outdoors'), ('Health', 'Health & Wellness'), ('Automotive', 'Automotive'), ('Pets', 'Pet Supplies'), ('Home Appliances', 'Home Appliances'), ('Office Supplies', 'Office Supplies'), ('Baby Products', 'Baby Products'), ('Music', 'Music & Instruments')], max_length=100),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
